// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZxEbSEcwg67LlGN9WR2RV4vlHLEj60hs',
    appId: '1:355145089175:web:b2b0476753f5ef2f4de9d2',
    messagingSenderId: '355145089175',
    projectId: 'whatsapp-909c2',
    authDomain: 'whatsapp-909c2.firebaseapp.com',
    storageBucket: 'whatsapp-909c2.firebasestorage.app',
    measurementId: 'G-L5RJE56WH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnM4t2S1uSys_-w7n19pmS_SlPiaRPgKs',
    appId: '1:355145089175:android:834e9f5fec27f52f4de9d2',
    messagingSenderId: '355145089175',
    projectId: 'whatsapp-909c2',
    storageBucket: 'whatsapp-909c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5foZin_m_L08dUlNYCrHPqBxdgIfu6Nc',
    appId: '1:355145089175:ios:56c6c73b45ab2d184de9d2',
    messagingSenderId: '355145089175',
    projectId: 'whatsapp-909c2',
    storageBucket: 'whatsapp-909c2.firebasestorage.app',
    iosBundleId: 'com.example.carCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5foZin_m_L08dUlNYCrHPqBxdgIfu6Nc',
    appId: '1:355145089175:ios:56c6c73b45ab2d184de9d2',
    messagingSenderId: '355145089175',
    projectId: 'whatsapp-909c2',
    storageBucket: 'whatsapp-909c2.firebasestorage.app',
    iosBundleId: 'com.example.carCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZxEbSEcwg67LlGN9WR2RV4vlHLEj60hs',
    appId: '1:355145089175:web:390881d6373d17fb4de9d2',
    messagingSenderId: '355145089175',
    projectId: 'whatsapp-909c2',
    authDomain: 'whatsapp-909c2.firebaseapp.com',
    storageBucket: 'whatsapp-909c2.firebasestorage.app',
    measurementId: 'G-6VF9EK4QWG',
  );
}
